version: "3.5"
services:
  mysql:
    container_name: mysql-${TIMEZONE_SLUG}
    image: mysql-custom:${TIMEZONE_SLUG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - mysql-dates
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
networks:
  mysql-dates:
